version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - chrono
  - clippy
  - crds
  - gensonnet
  - jsonnet
  - justfile
  - libsonnet
  - reqwest
  - rstest
  - serde
  - shellexpand
  - thiserror
  - walkdir
ignoreWords: []
import: []
