apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.test.com
spec:
  group: test.com
  names:
    kind: Example
    listKind: ExampleList
    plural: examples
    singular: example
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "The name of the example"
                description:
                  type: string
                  description: "A description of the example"
                enabled:
                  type: boolean
                  description: "Whether the example is enabled"
                count:
                  type: integer
                  minimum: 0
                  description: "The count value"
                tags:
                  type: array
                  items:
                    type: string
                  description: "List of tags"
              required:
                - name
                - enabled
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Running", "Succeeded", "Failed"]
                  description: "The current phase of the example"
                message:
                  type: string
                  description: "A human-readable message"
                lastUpdateTime:
                  type: string
                  format: date-time
                  description: "Last update timestamp"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Status
          type: string
          jsonPath: .status.phase
