[package]
name = "jsonnet-crd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tracing = "0.1"
walkdir = "2.3"
