# Default configuration for Gensonnet Docs theme
base_url = "http://127.0.0.1:1111"
title = "Gensonnet Documentation"
description = "Documentation for the Gensonnet project"
default_language = "en"

# Build configuration
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
compile_sass = true

# Markdown configuration
[markdown]
toc = true
external_links_target_blank = true
external_links_no_follow = true
highlight_code = true
highlight_theme = "solarized-light"

# Taxonomies
taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true },
]

# Extra configuration
[extra]
github_url = "https://github.com/goedelsoup/gensonnet-rs"
environment = "development"

# Theme options
[extra.theme]
show_sidebar = true
show_breadcrumbs = true
show_toc = true
sidebar_width = "250px"
primary_color = "#3b82f6"
secondary_color = "#64748b"
