# Development configuration for Gensonnet-rs documentation site
# Copy this to config.toml for local development

base_url = "http://127.0.0.1:1111"
title = "Gensonnet-rs Documentation (Development)"
description = "Documentation for the Gensonnet-rs project - Development Version"
default_language = "en"

# Theme configuration
theme = ""

# Build configuration
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"

# Markdown configuration
markdown = { toc = true, external_links_target_blank = true, external_links_no_follow = true }

# Taxonomies
taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true },
]

# Menu configuration
[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Getting Started"
url = "/getting-started/"
weight = 2

[[menu.main]]
name = "Plugins"
url = "/plugins/"
weight = 3

[[menu.main]]
name = "API Reference"
url = "/api/"
weight = 4

[[menu.main]]
name = "Examples"
url = "/examples/"
weight = 5

# Extra configuration
[extra]
# Put any custom variables here
github_url = "https://github.com/goedelsoup/gensonnet-rs"
environment = "development"
