name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - 'book/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'book/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Zola
        uses: shalzz/zola-deploy-action@v0.17.0
        with:
          zola_version: '0.17.2'
          
      - name: Build site
        run: |
          cd book
          export BASE_URL="https://goedelsoup.github.io/gensonnet-rs"
          zola build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: book/public
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: site
          path: book/public
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/public
          force_orphan: true
